### PR TITLE
tests: JSON/JSONB field test addition

### LINKED ISSUE #19: types: possible to support both JSON/JSONB
Currently SQLAlchemy has JSONB support for PostgreSQL:
http://docs.sqlalchemy.org/en/latest/dialects/postgresql.html#sqlalchemy.dialects.postgresql.JSONB

However, it doesn't seem like it will go into JSONType in SQLAlchemy-Utils due to difficulties in making it behave nicely across DBs:
https://github.com/kvesteri/sqlalchemy-utils/pull/125

For Invenio-Records we could likely get along with using JSONB when on PostgreSQL (and stay with text no the other platforms), as all we basically do is get and put the entire JSON so comparators is less of an issue.

### PR DESCRIPTION
**Pull request by hachreak**
* Adds test for JSON/JSONB fields.  (closes #19)

Signed-off-by: Leonardo Rossi <leonardo.r@cern.ch>

### CODE REVIEW

**Comment by jirikuncar** [comment]
It doesn't solve the problem with a Variant field.

duplicate of #58

**Comment by hachreak** [comment]
I'm testing different queries from yours.
BTW, the [with_variant()](https://travis-ci.org/hachreak/invenio-db/builds/177994229) looks working properly on PostgreSQL.

**Comment by jirikuncar** [comment]
Sure the queries on base JSON type work and there is no need in duplicating SQLAlchemy tests here. The problem is with specific PostgreSQL and Variant field.

**Comment by hachreak** [comment]
Problem looks [resolved](https://bitbucket.org/zzzeek/sqlalchemy/issues/3859/variant-does-not-transfer-expression)
```
js = sa.Column(sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'),)
```
And query:
```
session.query(table).filter(sa.cast(table.js['hello'], sa.String) == sa.type_coerce('world', sa.JSON)).first()
```
It works on mysql and postgresql.

**Pull request closed without merging**
