### PR TITLE
tests: example/app.py -> examples/app.py

### LINKED ISSUE #49: tests: example/app.py -> examples/app.py
It'd be good to rename `example/app.py` to `examples/app.py`.

Invenio-DB is the only Invenio 3 package that uses singular instead of plural.

### PR DESCRIPTION
**Pull request by alizeepace**
closes #49

Signed-off-by: Alizee Pace <alizee.pace@gmail.com>

### CODE REVIEW

**Comment by tiborsimko** [comment]
Can you please also amend `MANIFEST.in` accordingly?

- remove `prune example`
- add `recursive-include examples *.py`

**Comment by hachreak** [comment]
Hi @alizeepace,
there is any news about this PR? :)

**Comment by alizeepace** [comment]
@hachreak I just rebased against latest master, if the Travis CI passes I think it'll be ready for merge.

**Comment by hachreak** [comment]
@alizeepace thanks :smile:

**Pull request merged**
